### PR TITLE
enhance implementations and fix bugs.

### PR DESCRIPTION
**Pull request by scruel**
I‘m working on this project, all commits are following, please check it out when you have time.
(I may do something wrong like Refactoring code based my own behaviour, 
and if it happened, please let me know so I can make it right. )
WIP

### CODE REVIEW

**Comment by EgorKulikov** [comment]
I'd like to merge most of this, but will do so in parts and without changing code style

**Comment by scruel** [comment]
thanks, my bad, I changed a lot, but forgot to split it into parts. by the way, for the code style part, I do think some code style should try to optimize. Do you think so? Waiting for your reply.

**Comment by EgorKulikov** [comment]
I am in the process of cherry-picking changes from this pr, they will go either into 4.4.1 or 4.4.2. After that if you have any more usefull changes we can work on integrating them as well

**Comment by scruel** [comment]
Glad to know the progress of merging my pr. I have been busy with another personal project and haven't checked your project changes for a long time. It seems that you have pushed a lot of changes. I'd like to continue this work after my little project is completed.
So should I wait for you to merge now, or commit changes to resolve conflicts, or something else?
If there is anything I can off any help, please let me know.

**Comment by scruel** [comment]
@EgorKulikov
After huge changes in this project and I may have some leisure time now, in order to reduce your work of cherry-picking. I think I can split this PR as your wish by re-fork(or create a new branch) then re-PR it? what's your suggestions? After getting your permission, I will launch this idea and work on it soon.
Sorry for the inconvenience.

Plus, using third-party libraries works fine, but not such elegant, I used to remember that this project built by Maven, but hell it not...
Perhaps Gradle is more suitable for plugin development, as @ntviet18 tried before.

So after tried it today, I sorted out the following steps may help you add Gradle support, and I think such as [Apache Commons](https://mvnrepository.com/artifact/commons-lang/commons-lang
) and [Jackson](https://mvnrepository.com/search?q=jackson) libraries can use Gradle too.

1. Read the [official guide](https://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/prerequisites.html#add-gradle-support-to-an-existing-plugin).
2. Create build.gradle as step 1 mentioned.
3. Move files to Gradle project excepted directories.(see #67 or [my commit here](https://github.com/scruel/idea-chelper/commit/6b24f651d613791c3a25e2dc1564245b57fad22c)).
4. Run 'Gradle cleanIdea idea' as step 1 mentioned(Gradle environment required).
5. Close project
6. File -> New -> Project from Existing Sources, import this project with Gradle:
image

Here is my commit(see build.gradle): 
https://github.com/scruel/idea-chelper/commit/6b24f651d613791c3a25e2dc1564245b57fad22c

Or simply try to merge PR without all above steps? -> Failed for me.

Thx.

**Pull request closed without merging**
